### ISSUE TITLE
Can I use this sdk with different factory address?

### ISSUE THREAD

**Issue by zeroarst** [Uniswap/v2-sdk#102]
I have seen this topic: https://github.com/Uniswap/v2-sdk/issues/55
It just exported `computePairAddress` so we can call it with factory address to get the pair address.
However, if I we want to instantiate a Pair class, it still calls `Pair.getAddress` inside the contructor, which still uses its `computePairAddress({ factoryAddress: FACTORY_ADDRESS, tokenA, tokenB })`..

Is there a way I can instantiate a Pair class with custom factory address?

**Comment by vladikopl01** [comment]
@zeroarst Please, explain what you have done to make it possible. Having the same issue right now
